name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker BuildKit
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run build in dev container
        uses: stuartleeks/devcontainer-build-run@v0.2
        with:
          # NOTE - Change the image name below to match your fork
          imageName: ghcr.io/chrmarti/vscode-remote-try-rust-devcontainer
          # build and show the contents of the folder (to show the compiled app)
          runCmd: |
            cargo build
            ls -al
            terraform -version
